### ISSUE TITLE
感觉这种需求用nwjs，太重了。顺便打个广告

### ISSUE THREAD

**Issue by kkocdko** [qinlili23333/nw.Flash#1]
https://lanzoui.com/b00zo6rng
单文件打包，体积仅 `22 MB` ，自用的世界之窗浏览器（Chromium 48）改版，集成 Flash 29（最后一个不锁区版本）
由于使用了 Flash 的网站都很陈旧，所以 Chromium 48 也不会遇到新特性不支持的情况。
同样支持传参。改后缀名为 `.7z` 解压可得内容。

**Comment by qinlili23333** [comment]
nwjs可以用vulkan渲染了,高分屏性能毕竟好一点

**Comment by kkocdko** [comment]
> nwjs可以用vulkan渲染了,高分屏性能毕竟好一点

那好吧。不过大连铁务部大概也用不上有Vulkan支持的设备 ╭(╯^╰)╮

**Comment by qinlili23333** [comment]
你打包的时候好像把语言文件弄丢了,我尝试了英文和日文win10都打不开

**Comment by kkocdko** [comment]
我把其他语言都砍掉了。。。不过打不开这有点奇怪，我再改下。

**Comment by kkocdko** [comment]
已更新，能否再帮忙测试下？如果出错，尽量告诉我具体情况。
在中文系统上仅保留英文语言包，是可以正常使用的。按理其他语言系统也应该能用才对，不清楚为啥会出问题。。。（摊手）

**Comment by qinlili23333** [comment]
可以打开了，但是关闭后提示要用兼容性设置安装

**Comment by kkocdko** [comment]
我有空再研究下程序兼容性助手的机制。。。

**Comment by kkocdko** [comment]
高考结束勒~
已经尝试修复，如果有空的话，可以再帮忙测试下吗？
麻烦大佬咯~

**Comment by lingr7** [comment]
> 高考结束勒~ 已经尝试修复，如果有空的话，可以再帮忙测试下吗？ 麻烦大佬咯~
win10可以正常打开，免安装打开。
